---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## **Teach Me How to Google**

Googling for code help is something that all data scientists (at all career stages) do. But figuring out how to get the information you need back can be incredibly challenging, particularly for new coders. In this workshop, we’ll discuss strategies for refining your queries to increase your chances of finding informative solutions.

---

This talk was originally developed by [Samantha Csik](https://samanthacsik.github.io/), Data Training Coordinator at the National Center for Ecological Analysis & Synthesis (NCEAS) for the Bren School's (UCSB) Master's of Environmental Data Science (MEDS) program. 

The original slides can be found on the [UCSB-MEDS GitHub Organization](https://github.com/UCSB-MEDS/teach-me-how-to-google). Slides have been adapted for a number of presentations. Versions are organized by date below:

* [**Master of Techology Management, Winter 2022**](slides/MTM-2022-01-06.html)  
*January 6th, 2022*

* [**Master of Environmental Data Science, Fall 2021 (original slides)**](slides/MEDS-2021-10-11.html)  
*October 10th, 2021*